server:
  port: 8081
  servlet:
    context-path: /api

spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/bookspa}
    username: ${DATASOURCE_USERNAME:bookspa}
    password: ${DATASOURCE_PASSWORD:bookspa}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddlAuto: update

  mail:
    host: ${SMTP_HOST:smtp.example.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:example}
    password: ${SMTP_PASSWORD:secure}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub

logging:
  level:
    org:
      springframework:
        security: DEBUG

redkokia:
  senderEmail: notifications@redkokia.com
  bccEmail: gracious.mashasha@gmail.com

