server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: ${RK_DATASOURCE_URL}
    username: ${RK_DATASOURCE_USERNAME}
    password: ${RK_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddlAuto: update

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub

logging:
  level:
    org:
      springframework:
        security: DEBUG