server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: ${RK_DATASOURCE_URL}
    username: ${RK_DATASOURCE_USERNAME}
    password: ${RK_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddlAuto: update
