server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: ${RK_DATASOURCE_URL}
    username: ${RK_DATASOURCE_USERNAME}
    password: ${RK_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddlAuto: update

  mail:
    host: ${RK_SMTP_HOST}
    port: ${RK_SMTP_PORT}
    username: ${RK_SMTP_USERNAME}
    password: ${RK_SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub

logging:
  level:
    org:
      springframework:
        security: DEBUG

redkokia:
  senderEmail: notifications@redkokia.com
  bccEmail: gracious.mashasha@gmail.com

